spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5000/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
onefit:
  otp:
    retry-wait-time: 5 # in seconds
    retry-count: 3
    time-to-live: 60 # in seconds:
  notification:
    sms:
      eskiz: #eskiz token
  security:
    token:
      expiration: 86400
      secret: SzqXrBuEVJOVLqjGeenHM6aNo8j3KJiKJ4LWB3oZf8aSlkkQgw6L6ZwklCbQK2Y/

