spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5000/postgres
  jpa.show-sql: true
  jpa:
    properties:
      hibernate:
        format_sql: true
