insert into permission(name)
values ('category:create'),
       ('category:read'),
       ('category:update'),
       ('category:delete'),
       ('studio:create'),
       ('studio:read'),
       ('studio:update'),
       ('studio:delete'),
       ('studio:add-category'),
       ('location:create'),
       ('location:read'),
       ('location:update'),
       ('location:delete'),
       ('comment:create'),
       ('comment:read'),
       ('comment:delete'),
       ('course:create'),
       ('course:read'),
       ('course:update'),
       ('course:delete'),
       ('rating:create'),
       ('rating:read'),
       ('rating:delete'),
       ('feedback:create'),
       ('feedback:read'),
       ('feedback:update'),
       ('feedback:delete'),
       ('liked:create'),
       ('liked:read'),
       ('liked:update'),
       ('liked:delete'),
       ('membership:create'),
       ('membership:read'),
       ('membership:update'),
       ('membership:delete'),
       ('history:read');

insert into role(name)
values ('ADMIN');
insert into role(name)
values ('USER');

insert into role_permission(role_id, permission_id)
values ((select name from role where name = 'USER'), (select  name from permission where name = 'comment:create')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'comment:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'comment:delete')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'rating:create')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'course:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'category:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'history:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'liked:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'location:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'feedback:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'studio:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'membership:read')),
       ((select name from role where name = 'USER'), (select  name from permission where name = 'membership:create'));

insert into role_permission(role_id, permission_id)
values ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'studio:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'studio:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'studio:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'studio:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'studio:add-category')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'location:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'location:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'location:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'location:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'comment:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'comment:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'comment:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'course:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'course:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'course:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'course:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'feedback:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'feedback:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'feedback:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'feedback:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'liked:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'liked:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'liked:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'liked:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'membership:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'membership:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'membership:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'membership:delete'));