package com.example.onefitclone.rating;

public enum RatingNameEnum {
    CLEANLINESS_OF_THE_DRESSING_ROOM,
    CLEANLINESS_OF_THE_ROOM,
    TRAINER_PROFESSIONALISM,
    CONDITION_OF_THE_EQUIPMENT,
    SERVICE_QUALITY
}